\033[0;32mtodos:\033[0m
    [0;36mtitle[0m: Cyclic Boundaries 
    [0;36mdescription[0m: Implement the correct boundary conditions on the spins 
    [0;36mtitle[0m: Header Files 
    [0;36mdescription[0m: Move a large portion of the logic into header files including one for general utilities and then one per question. 
    [0;36mtitle[0m: Command Line Interface 
    [0;36mdescription[0m: Set up a command line interface so that the question to run can be selected as a CLI argument 
    [0;36mtitle[0m: Energy 
    [0;36mdescription[0m: Check that the energy calculation for the energy changes is actually correct and if not then use the whole ensamble 
    [0;36mtitle[0m: Array Length 
    [0;36mdescription[0m: It is not possible to have a length function in C. Need to use a macro instead I think 
    [0;36mtitle[0m: Configuration File 
    [0;36mdescription[0m: Add a configuration file in order to share the same file names throughout the script files 
    [0;36mtitle[0m: Legacy 
    [0;36mdescription[0m: Fix the legacy issues in the bash script now that the scope of the project has expanded 
    [[0;36mtitle[[0m: Data 
    [[0;36mdescription[[0m: Format the data in an array so that it can be written to the file in a single hit 
