[reps]
    number = 100000

[temperatures]
    low = .5
    high = 3.
    step = .1

[spins]
    number = 100

[task]
    index = physical_parameters 

[dimensions]
    number = 1

[out]
    address = pub/data/1c.csv 
