[readables]
    1a = pub/data/1a.csv
    1c = pub/data/1c.csv
    1e = pub/data/1e.csv

[executable]
    exe = out/project

[publishable]
    pub = pub/report.tex

[viewable]
    view = pub/figures.gpi

[extras]
    e1 = pub/report.aux
    e2 = pub/report.log

