[reps]
    number = 10000

[temperatures]
    low = 0.
    high = 4.
    step = .1

[spins]
    number = 100

[task]
    index = physical_parameters 

[dimensions]
    number = 1

[out]
    address = pub/data/1c.csv 
