[reps]
    number = 1000

[temperatures]
    low = 1.
    high = 4.
    step = 1.

[spins]
    number = 500

[task]
    index = first_and_last 

[dimensions]
    number = 1

[out]
    address = pub/data/1c.csv 
