[reps]
    number = 1000

[temperatures]
    low = .1
    high = 4.
    step = 1.
    reps = 1000

[spins]
    number = 500

[task]
    index = histogram

[dimensions]
    number = 1

[out]
    address = pub/data/1e.csv 
