[reps]
    number = 10000

[temperatures]
    low = .1
    high = 4.
    step = 1.

[spins]
    number = 10000

[task]
    index = first_and_last

[dimensions]
    number = 2

[out]
    address = pub/data/2a.csv 
